export const OPTION_LIST_REQUEST = 'OPTION_LIST_REQUEST';
export const OPTION_LIST_SUCCESS = 'OPTION_LIST_SUCCESS';
export const OPTION_LIST_FAIL = 'OPTION_LIST_FAIL';

export const OPTION_DETAILS_REQUEST = 'OPTION_DETAILS_REQUEST';
export const OPTION_DETAILS_SUCCESS = 'OPTION_DETAILS_SUCCESS';
export const OPTION_DETAILS_FAIL = 'OPTION_DETAILS_FAIL';